### ISSUE TITLE
Execute online aggregation queries

### ISSUE THREAD

**Issue by doflink** [InitialDLab/XDB#1] opened 2017-05-29 19:30 UTC
Hi,

Nice work! I try to run your system. However, when I execute the online aggregation queries, I got the following error:

`psql -d tpch <  ./queries/query10_online.sql`

> Timing is on.
ERROR:  syntax error at or near "("
LINE 1: SELECT ONLINE SUM(l_extendedprice * (1 - l_discount))
                         ^
Time: 0.246 ms 

Could you please help me to handle the issue?

Thanks!

**Comment by zzy7896321** [comment] 2017-05-30 15:49
Hi,

Thank you for trying our system.

The reason might be that the PostgreSQL in PATH is not the version compiled from this repository.  Could you check if the installation is in your PATH environment variable?

Let me know if there's still problem.

Zhuoyue

**Comment by zzy7896321** [comment] 2017-06-02 05:17
Hi,

Does it solve the problem? If the issue is resolved, I'll close the issue. Thanks!

Zhuoyue

**Comment by doflink** [comment] 2017-06-02 06:01
It works!
Thanks!

**Closed as completed** 2017-06-02 06:01 UTC
